version: '3.8'

networks:
  app-network:
    driver: bridge

services:
  app:
    build:
      context: ./app
      dockerfile: dockerfile
    container_name: app_container
    tty: true
    volumes:
      - ./app:/usr/src/app
    networks:
      - app-network
  
  nginx:
    build:
      context: ./nginx
      dockerfile: dockerfile
    container_name: nginx_container
    networks:
      - app-network
    ports:
      - "8080:80"
    depends_on:
      - app

  db:
    image: mysql:latest
    container_name: db_container
    restart: always
    networks:
      - app-network
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: app_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "33061:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql
